/*
 * Hibernate, Relational Persistence for Idiomatic Java
 *
 * License: GNU Lesser General Public License (LGPL), version 2.1 or later.
 * See the lgpl.txt file in the root directory or <http://www.gnu.org/licenses/lgpl-2.1.html>.
 */
package org.hibernate.dialect.identity;

/**
 * @author loiclefevre (loic.lefevre@gmail.com)
 */
public class Oracle19cIdentityColumnSupport extends Oracle12cIdentityColumnSupport {
	@Override
	public String getIdentityColumnString(int type) {
		return "generated by default as identity ( cache 50 )";
	}
}
